name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2

      # install NPM dependencies and Cypress
      # https://github.com/cypress-io/github-action
      - name: Install 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      # start application in the background
      # and pass Sendgrid info by injecting the project's secrets
      - name: Start the app 🚦
        run: npm start &
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_FROM: ${{ secrets.SENDGRID_FROM }}

      # run Cypress tests
      - name: E2E tests 🧪
        uses: cypress-io/github-action@v2
        with:
          # we already installed everything
          install: false
          # make sure the app has fully started
          wait-on: 'http://localhost:3000'
          # run Percy program that would run Cypress
          # and forward snapshots to the Percy service
          command-prefix: 'percy exec -- npx'
        # inject the Percy token
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
